### ISSUE TITLE
Myanmar Language Syllable Break with PHP

### ISSUE THREAD

**Issue by phyozawtun** [ye-kyaw-thu/sylbreak#5]
Hello, 

For SEO optimization, I need to run this function on a PHP project. This project is widely covered in various areas but unfortunately not PHP. So I did some research and make the PHP snippet. I hope this issue report and attached PHP snippet would help to Repository maintainer.

```
<?php
$string = 'သီဟိုဠ်မှ ဉာဏ်ကြီးရှင်သည် အာယုဝဍ္ဎနဆေးညွှန်းစာကို ဇလွန်ဈေးဘေး ဗာဒံပင်ထက် အဓိဋ္ဌာန်လျက် ဂဃနဏဖတ်ခဲ့သည်။';
$pattern = "/(?:(?<!\x{1039})([\\x{1000}-\\x{102A}\\x{103F}\\x{104A}-\\x{104F}]|[\\x{1040}-\\x{1049}]+|[^\\x{1000}-\\x{104F}]+)(?![\\x{103E}\\x{103B}]?[\\x{1039}\\x{103A}\\x{1037}]))/uim";
$replacement = '|$1';
echo preg_replace($pattern, $replacement, $string);
//Output |သီ|ဟိုဠ်|မှ| |ဉာဏ်|ကြီး|ရှင်|သည်| |အာ|ယု|ဝဍ္ဎ|န|ဆေး|ညွှန်း|စာ|ကို| |ဇ|လွန်|ဈေး|ဘေး| |ဗာ|ဒံ|ပင်|ထက်| |အ|ဓိဋ္ဌာန်|လျက်| |ဂ|ဃ|န|ဏ|ဖတ်|ခဲ့|သည်|။
?>
```

**Comment by ye-kyaw-thu** [comment]
Thank you for your email!
ကျေးဇူးပါ။ ဆရာ အားတဲ့အခါ Java, PHP ပြန်ကြည့်ပြီး sylbreak ကို update
လုပ်ပါမယ် ....

y

**Comment by phyozawtun** [comment]
ဟုတ်ကဲ့ပါ ဆရာ၊ ကျွန်တော် Contribute လို့ရတာရှိလည်း ပြောပါ ခင်ဗျ။
